/**
 * PrivateTwo Ephemeral Signaling Server
 *
 * STRICT PRIVACY GUARANTEES:
 * 1. ZERO PERSISTENT STORAGE: No databases, no disk writes, no message caching.
 * 2. EPHEMERAL RELAY ONLY: Sockets relay end-to-end encrypted payloads and WebRTC SDP/ICE.
 * 3. STRICT 2-DEVICE LIMIT: Rooms accept exactly two devices. Any 3rd device is instantly rejected.
 * 4. SHORT-LIVED PAIRING CODES: Pairing rendezvous codes expire in 180 seconds.
 */

const http = require('http');
const { WebSocketServer, WebSocket } = require('ws');

const PORT = process.env.PORT || 8088;
const PAIRING_CODE_TTL_MS = 180 * 1000; // 3 minutes

const server = http.createServer((req, res) => {
    if (req.url === '/health') {
        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ status: 'healthy', activeSessions: sessions.size }));
    } else {
        res.writeHead(200, { 'Content-Type': 'text/plain' });
        res.end('PrivateTwo Ephemeral Signaling Server. No content is stored.');
    }
});

const wss = new WebSocketServer({ server });

const pairingCodes = new Map();
const sessions = new Map();
const wsToSession = new Map();
const deviceIdToWs = new Map();
const pendingPairings = new Map(); // deviceId -> { sessionId, peerDeviceId }

function safeSend(ws, payload) {
    if (!ws || ws.readyState !== WebSocket.OPEN) return false;
    try {
        const data = typeof payload === 'string' ? payload : JSON.stringify(payload);
        ws.send(data, (err) => {
            if (err) console.error(`[Signaling] safeSend callback error: ${err.message}`);
        });
        return true;
    } catch (err) {
        console.error(`[Signaling] safeSend exception: ${err.message}`);
        return false;
    }
}

wss.on('connection', (ws, req) => {
    ws.isAlive = true;
    const clientIp = req.socket.remoteAddress;
    console.log(`[Signaling] New WebSocket connection from ${clientIp}`);
    ws.on('pong', () => { ws.isAlive = true; });

    ws.on('message', (data) => {
        try {
            const message = JSON.parse(data.toString());
            console.log(`[Signaling] Received message: ${message.type}`);
            handleMessage(ws, message);
        } catch (err) {
            console.error(`[Signaling] Malformed JSON: ${err.message}`);
            sendError(ws, 'MALFORMED_JSON', 'Invalid JSON message payload');
        }
    });

    ws.on('close', () => {
        console.log(`[Signaling] Client disconnected`);
        handleDisconnect(ws);
    });

    ws.on('error', (err) => {
        console.error(`[Signaling] Socket error: ${err.message}`);
        handleDisconnect(ws);
    });
});

function handleMessage(ws, msg) {
    const type = msg.type;

    // Track deviceId to socket mapping if present
    if (msg.deviceId) {
        deviceIdToWs.set(msg.deviceId, ws);
        ws.deviceId = msg.deviceId;

        // Check if there is a pending pairing notification for this device
        if (pendingPairings.has(msg.deviceId)) {
            const pending = pendingPairings.get(msg.deviceId);
            pendingPairings.delete(msg.deviceId);
            wsToSession.set(ws, pending.sessionId);
            const session = sessions.get(pending.sessionId);
            if (session) {
                if (session.deviceAId === msg.deviceId) session.deviceA = ws;
                if (session.deviceBId === msg.deviceId) session.deviceB = ws;
            }
            safeSend(ws, {
                type: 'PEER_JOINED_PAIRING',
                sessionId: pending.sessionId,
                peerDeviceId: pending.peerDeviceId
            });
        }
    }

    switch (type) {
        case 'REGISTER_PAIRING_CODE': {
            const code = String(msg.code || '').replace(/\s+/g, '').trim();
            const deviceId = msg.deviceId;
            console.log(`[Signaling] Registering pairing code ${code} for device ${deviceId}`);
            if (!code || !deviceId) {
                return sendError(ws, 'INVALID_REQUEST', 'Missing code or deviceId');
            }

            // Clean any previous pairing code generated by this device
            for (const [c, entry] of pairingCodes.entries()) {
                if (entry.initiatorDeviceId === deviceId) {
                    clearTimeout(entry.timeoutId);
                    pairingCodes.delete(c);
                }
            }

            const timeoutId = setTimeout(() => {
                pairingCodes.delete(code);
                safeSend(ws, { type: 'PAIRING_CODE_EXPIRED', code });
            }, PAIRING_CODE_TTL_MS);

            pairingCodes.set(code, {
                initiatorWs: ws,
                initiatorDeviceId: deviceId,
                createdAt: Date.now(),
                timeoutId
            });

            safeSend(ws, { type: 'PAIRING_CODE_REGISTERED', code, expiresInSeconds: 180 });
            break;
        }

        case 'JOIN_PAIRING_CODE': {
            const code = String(msg.code || '').replace(/\s+/g, '').trim();
            const joinerDeviceId = msg.deviceId;
            const entry = pairingCodes.get(code);

            if (!entry) {
                console.warn(`[Signaling] Pairing code not found: "${code}". Active codes: [${Array.from(pairingCodes.keys()).join(', ')}]`);
                return sendError(ws, 'PAIRING_CODE_NOT_FOUND', 'Pairing code does not exist or has expired');
            }

            if (entry.initiatorDeviceId === joinerDeviceId) {
                return sendError(ws, 'CANNOT_PAIR_SELF', 'Cannot pair a device with itself');
            }

            clearTimeout(entry.timeoutId);
            pairingCodes.delete(code);

            // Find current active socket for initiator
            const activeInitiatorWs = deviceIdToWs.get(entry.initiatorDeviceId) || entry.initiatorWs;

            const sessionId = `session_${Date.now()}_${Math.random().toString(36).substring(2, 9)}`;
            const session = {
                id: sessionId,
                deviceA: activeInitiatorWs,
                deviceAId: entry.initiatorDeviceId,
                deviceB: ws,
                deviceBId: joinerDeviceId
            };

            sessions.set(sessionId, session);
            if (activeInitiatorWs) {
                wsToSession.set(activeInitiatorWs, sessionId);
            }
            wsToSession.set(ws, sessionId);

            if (activeInitiatorWs && activeInitiatorWs.readyState === WebSocket.OPEN) {
                safeSend(activeInitiatorWs, {
                    type: 'PEER_JOINED_PAIRING',
                    sessionId,
                    peerDeviceId: joinerDeviceId
                });
            } else {
                console.log(`[Signaling] Initiator offline during pairing, saving pending notification for ${entry.initiatorDeviceId}`);
                pendingPairings.set(entry.initiatorDeviceId, {
                    sessionId,
                    peerDeviceId: joinerDeviceId
                });
            }

            safeSend(ws, {
                type: 'PAIRING_ACCEPTED',
                sessionId,
                peerDeviceId: entry.initiatorDeviceId
            });
            break;
        }

        case 'JOIN_SESSION': {
            const sessionId = msg.sessionId;
            const deviceId = msg.deviceId;
            const expectedPeerId = msg.expectedPeerId;

            if (!sessionId || !deviceId || !expectedPeerId) {
                return sendError(ws, 'INVALID_REQUEST', 'Missing sessionId, deviceId, or expectedPeerId');
            }

            let session = sessions.get(sessionId);
            if (!session) {
                session = {
                    id: sessionId,
                    deviceA: ws,
                    deviceAId: deviceId,
                    deviceB: null,
                    deviceBId: expectedPeerId
                };
                sessions.set(sessionId, session);
                wsToSession.set(ws, sessionId);
                safeSend(ws, { type: 'SESSION_WAITING_FOR_PEER', sessionId });
            } else {
                const isExpected = (deviceId === session.deviceBId && expectedPeerId === session.deviceAId) ||
                                  (deviceId === session.deviceAId && expectedPeerId === session.deviceBId);

                if (!isExpected) {
                    return sendError(ws, 'UNAUTHORIZED_PEER', 'Identity does not match paired credentials');
                }

                if (session.deviceAId === deviceId) {
                    session.deviceA = ws;
                } else if (session.deviceBId === deviceId) {
                    session.deviceB = ws;
                } else if (!session.deviceA) {
                    session.deviceA = ws;
                    session.deviceAId = deviceId;
                } else if (!session.deviceB) {
                    session.deviceB = ws;
                    session.deviceBId = deviceId;
                } else {
                    // Session full with 2 different other devices
                    return sendError(ws, 'SESSION_FULL', 'Max 2 devices allowed. Third device rejected.');
                }

                wsToSession.set(ws, sessionId);

                const peerWs = (session.deviceA === ws) ? session.deviceB : session.deviceA;
                safeSend(ws, { type: 'PEER_CONNECTED', peerDeviceId: expectedPeerId });
                if (peerWs) {
                    safeSend(peerWs, { type: 'PEER_CONNECTED', peerDeviceId: deviceId });
                }
            }
            break;
        }

        case 'PAIR_HANDSHAKE':
        case 'SDP_OFFER':
        case 'SDP_ANSWER':
        case 'ICE_CANDIDATE':
        case 'CALL_OFFER':
        case 'CALL_ANSWER':
        case 'CALL_END':
        case 'E2EE_ENVELOPE': {
            const sessionId = wsToSession.get(ws);
            if (!sessionId) {
                return sendError(ws, 'NOT_IN_SESSION', 'Device is not part of an active session');
            }

            const session = sessions.get(sessionId);
            if (!session) {
                return sendError(ws, 'SESSION_EXPIRED', 'Session does not exist');
            }

            const partnerWs = (session.deviceA === ws) ? session.deviceB : session.deviceA;
            if (!partnerWs || partnerWs.readyState !== WebSocket.OPEN) {
                return sendError(ws, 'PEER_OFFLINE', 'Partner device is currently offline');
            }

            safeSend(partnerWs, msg);
            break;
        }

        default:
            sendError(ws, 'UNKNOWN_MESSAGE_TYPE', `Unknown type: ${type}`);
    }
}

function handleDisconnect(ws) {
    if (ws.deviceId && deviceIdToWs.get(ws.deviceId) === ws) {
        deviceIdToWs.delete(ws.deviceId);
    }
    const sessionId = wsToSession.get(ws);
    if (sessionId) {
        wsToSession.delete(ws);
        const session = sessions.get(sessionId);
        if (session) {
            const partnerWs = (session.deviceA === ws) ? session.deviceB : session.deviceA;
            if (partnerWs) {
                safeSend(partnerWs, { type: 'PEER_DISCONNECTED' });
            }
            if (session.deviceA === ws) session.deviceA = null;
            if (session.deviceB === ws) session.deviceB = null;

            if (!session.deviceA && !session.deviceB) {
                sessions.delete(sessionId);
            }
        }
    }
}

function sendError(ws, code, message) {
    safeSend(ws, { type: 'ERROR', code, message });
}

setInterval(() => {
    wss.clients.forEach((ws) => {
        if (!ws.isAlive) {
            handleDisconnect(ws);
            return ws.terminate();
        }
        ws.isAlive = false;
        ws.ping();
    });
}, 30000);

server.listen(PORT, () => {
    console.log(`PrivateTwo Signaling Server listening on port ${PORT}`);
    console.log(`Ephemeral mode active: ZERO data stored.`);
});
